from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from lolpaths.validator import load_valid_rules

HEADER = "# Generated by LOLPaths. Do not edit manually.\n"
PLATFORMS = ("windows", "linux", "macos")


def generate_outputs(
    rules_dir: Path,
    schema_path: Path,
    output_dir: Path,
    docs_dir: Path | None = None,
) -> None:
    rules = load_valid_rules(rules_dir, schema_path)
    output_dir.mkdir(parents=True, exist_ok=True)

    entries = sorted(
        _path_entries(rules), key=lambda item: (item["path"], item["platform"], item["rule_id"])
    )
    for platform in PLATFORMS:
        _write_platform(output_dir / f"{platform}.txt", entries, platform)
    if docs_dir is not None:
        _write_docs_outputs(docs_dir, rules, entries)


def _path_entries(rules: list[dict[str, Any]]) -> list[dict[str, str]]:
    entries: dict[tuple[str, str, str], dict[str, str]] = {}
    for rule in rules:
        for matcher in rule.get("match", {}).get("paths", []):
            for platform in matcher.get("platforms", []):
                key = (matcher["path"], platform, rule["id"])
                entries[key] = {
                    "path": matcher["path"],
                    "platform": platform,
                    "kind": matcher["kind"],
                    "rule_id": rule["id"],
                    "name": rule["name"],
                }
    return list(entries.values())


def _write_platform(path: Path, entries: list[dict[str, str]], platform: str) -> None:
    seen: set[str] = set()
    lines = [HEADER]
    for entry in entries:
        if entry["platform"] != platform or entry["path"] in seen:
            continue
        seen.add(entry["path"])
        lines.append(f"{entry['path']}\n")
    path.write_text("".join(lines), encoding="utf-8")


def _write_rules_json(path: Path, rules: list[dict[str, Any]]) -> None:
    payload = {"schema_version": 1, "rules": rules}
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _write_docs_outputs(
    docs_dir: Path,
    rules: list[dict[str, Any]],
    entries: list[dict[str, str]],
) -> None:
    api_dir = docs_dir / "public" / "api"
    docs_content_dir = docs_dir / "content" / "docs"
    api_dir.mkdir(parents=True, exist_ok=True)
    docs_content_dir.mkdir(parents=True, exist_ok=True)

    _write_rules_json(api_dir / "rules.json", rules)
    _write_stats_json(api_dir / "stats.json", rules, entries)
    _clean_generated_rule_docs(docs_content_dir)

    for rule in rules:
        (docs_content_dir / f"{rule['id']}.mdx").write_text(
            _rule_markdown(rule),
            encoding="utf-8",
        )


def _write_stats_json(
    path: Path,
    rules: list[dict[str, Any]],
    entries: list[dict[str, str]],
) -> None:
    categories = sorted({rule["category"] for rule in rules})
    platforms = sorted({entry["platform"] for entry in entries})
    payload = {
        "schema_version": 1,
        "rules": len(rules),
        "categories": len(categories),
        "critical": sum(1 for rule in rules if rule["sensitivity"] == "critical"),
        "platforms": platforms,
        "path_matchers": _path_matcher_count(rules),
    }
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _path_matcher_count(rules: list[dict[str, Any]]) -> int:
    return sum(len(rule.get("match", {}).get("paths", [])) for rule in rules)


def _clean_generated_rule_docs(docs_content_dir: Path) -> None:
    marker = "{/* Generated by lolpaths generate. Do not edit manually. */}"
    for path in docs_content_dir.glob("*.mdx"):
        if marker in path.read_text(encoding="utf-8"):
            path.unlink()

    legacy_dir = docs_content_dir / "rules"
    if not legacy_dir.exists():
        return
    for path in legacy_dir.glob("*.mdx"):
        if marker in path.read_text(encoding="utf-8"):
            path.unlink()
    meta_path = legacy_dir / "meta.json"
    if meta_path.exists() and not list(legacy_dir.glob("*.mdx")):
        meta_path.unlink()
    if not any(legacy_dir.iterdir()):
        legacy_dir.rmdir()


def _rule_markdown(rule: dict[str, Any]) -> str:
    lines = [
        "---",
        f"title: {rule['name']}",
        f"description: {_frontmatter_description(rule)}",
        "icon: FileCode2",
        "---",
        "",
        "{/* Generated by lolpaths generate. Do not edit manually. */}",
        "",
        "## Metadata",
        "",
        f"- id: `{rule['id']}`",
        f"- category: `{rule['category']}`",
        f"- sensitivity: `{rule['sensitivity']}`",
    ]

    if rule.get("subcategory"):
        lines.append(f"- subcategory: `{rule['subcategory']}`")
    if rule.get("artifact_types"):
        lines.append(f"- artifact types: {_code_list(rule['artifact_types'])}")
    if rule.get("tags"):
        lines.append(f"- tags: {_code_list(rule['tags'])}")

    lines.extend(["", "## Path Matchers", ""])
    paths = rule.get("match", {}).get("paths", [])
    if paths:
        lines.extend(_path_table(paths))
    else:
        lines.append("This rule has no path matchers.")

    content = rule.get("match", {}).get("content", {})
    if content:
        lines.extend(["", "## Content Indicators", ""])
        if content.get("contains"):
            lines.extend(["Literal strings:", ""])
            lines.extend(f"- `{value}`" for value in content["contains"])
        if content.get("regex"):
            if content.get("contains"):
                lines.append("")
            lines.extend(["Regular expressions:", ""])
            lines.extend(f"- `{value}`" for value in content["regex"])

    if rule.get("credentials"):
        lines.extend(["", "## Credential Types", ""])
        lines.extend(f"- `{value}`" for value in rule["credentials"].get("types", []))

    if rule.get("impact"):
        lines.extend(["", "## Impact", ""])
        for key, value in sorted(rule["impact"].items()):
            if value:
                lines.append(f"- `{key}`")

    if rule.get("references"):
        lines.extend(["", "## References", ""])
        for reference in rule["references"]:
            lines.append(f"- [{reference['name']}]({reference['url']})")

    return "\n".join(lines).rstrip() + "\n"


def _frontmatter_description(rule: dict[str, Any]) -> str:
    description = _description(rule).replace("\n", " ").strip()
    escaped = description.replace('"', '\\"')
    return f'"{escaped}"'


def _description(rule: dict[str, Any]) -> str:
    return str(rule.get("description") or f"LOLPaths rule for {rule['name']}.").strip()


def _code_list(values: list[str]) -> str:
    return ", ".join(f"`{value}`" for value in values)


def _path_table(paths: list[dict[str, Any]]) -> list[str]:
    lines = ["| Path | Kind | Platforms |", "| --- | --- | --- |"]
    for matcher in paths:
        platforms = ", ".join(f"`{platform}`" for platform in matcher["platforms"])
        lines.append(f"| `{matcher['path']}` | `{matcher['kind']}` | {platforms} |")
    return lines
