from __future__ import annotations

import json
from pathlib import Path

from lolpaths.generator import generate_outputs


def write_rule(rules_dir: Path, name: str, text: str) -> None:
    path = rules_dir / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.strip() + "\n", encoding="utf-8")


def schema_path() -> Path:
    return Path(__file__).resolve().parents[1] / "schema" / "lolpaths.schema.json"


def test_generator_writes_deterministic_platform_outputs(tmp_path: Path) -> None:
    rules_dir = tmp_path / "rules"
    output_dir = tmp_path / "generated"
    write_rule(
        rules_dir,
        "application/sample-directory.yaml",
        """
schema_version: 1
id: application.sample-directory
name: Sample Directory
category: application
sensitivity: critical
match:
  paths:
    - path: "windows-sample-glob"
      kind: glob
      platforms: [windows]
    - path: "unix-sample-glob"
      kind: glob
      platforms: [linux, macos]
""",
    )
    write_rule(
        rules_dir,
        "application/sample-file.yaml",
        """
schema_version: 1
id: application.sample-file
name: Sample File
category: application
sensitivity: critical
match:
  paths:
    - path: "sample-credentials"
      kind: file
      platforms: [linux, macos]
""",
    )

    generate_outputs(rules_dir, schema_path(), output_dir)
    first = {path.name: path.read_text(encoding="utf-8") for path in output_dir.iterdir()}
    generate_outputs(rules_dir, schema_path(), output_dir)
    second = {path.name: path.read_text(encoding="utf-8") for path in output_dir.iterdir()}

    assert first == second
    assert set(first) == {"linux.txt", "macos.txt", "windows.txt"}
    assert "windows-sample-glob" in first["windows.txt"]
    assert "unix-sample-glob" in first["linux.txt"]
    assert "unix-sample-glob" in first["macos.txt"]
    assert "windows-sample-glob" not in first["linux.txt"]


def test_generator_writes_docs_api_and_rule_pages(tmp_path: Path) -> None:
    rules_dir = tmp_path / "rules"
    output_dir = tmp_path / "generated"
    docs_dir = tmp_path / "docs"
    write_rule(
        rules_dir,
        "application/sample-secret.yaml",
        """
schema_version: 1
id: application.sample-secret
name: Sample Secret
description: >
  Sample secrets used by generator tests.
category: application
artifact_types: [credential, private-key]
sensitivity: critical
match:
  paths:
    - path: "sample-key"
      kind: glob
      platforms: [linux, macos]
  content:
    regex:
      - '-----BEGIN OPENSSH PRIVATE KEY-----'
credentials:
  types: [private-key]
impact:
  credential_access: true
  remote_access: true
tags: [ssh, private-key]
metadata:
  confidence: high
""",
    )

    generate_outputs(rules_dir, schema_path(), output_dir, docs_dir)

    api_rules = json.loads((docs_dir / "public/api/rules.json").read_text(encoding="utf-8"))
    stats = json.loads((docs_dir / "public/api/stats.json").read_text(encoding="utf-8"))
    rule_page = docs_dir / "content/docs/application/sample-secret.mdx"
    flat_rule_page = docs_dir / "content/docs/application.sample-secret.mdx"

    assert api_rules["rules"][0]["id"] == "application.sample-secret"
    assert api_rules["rules"][0]["doc_path"] == "application/sample-secret"
    assert stats == {
        "schema_version": 1,
        "rules": 1,
        "categories": 1,
        "critical": 1,
        "platforms": ["linux", "macos"],
        "path_matchers": 1,
    }
    assert rule_page.exists()
    assert not flat_rule_page.exists()

    content = rule_page.read_text(encoding="utf-8")
    assert "{/* Generated by lolpaths generate. Do not edit manually. */}" in content
    assert "<!--" not in content
    assert "title: Sample Secret" in content
    assert "## Sample Secret" not in content
    assert content.count("Sample secrets used by generator tests.") == 1
    assert "id: `application.sample-secret`" in content
    assert "sample-key" in content
    assert "-----BEGIN OPENSSH PRIVATE KEY-----" in content
